### ISSUE TITLE
left_join() options "by=" not work in library(sparklyr)

### ISSUE THREAD

**Issue by p2004r** [hadley/dplyr#2325]
*_join() with by=c(XXX=YYY) produce error in some cases

Example code with error:

```
library(sparklyr)
library(dplyr)
library(ggplot2)

sc <- spark_connect("local", version="2.0.0")

test1 <- data.frame(V1=c(rep(c("M1", "M2", "M3"), 3)), V2 = 1:9,
                    V3_1 = rep(c(1,0,1),9*5/3),
                    V3_2 = rep(c(1,1,0),9*5/3))
test2 <- data.frame(V1=c(rep(c("M1", "M2", "M3"), 3)),
                    V2 = 1:(9*5),
                    V4=c(rep(c("M2", "M3", "M1"), 3)))

test1_tbl <- copy_to(sc, test1, "test1", overwrite = TRUE)
test2_tbl <- copy_to(sc, test2, "test2", overwrite = TRUE)

a <- test2_tbl %>%
    left_join(test1_tbl, by=c("V4"="V1")) %>%
    group_by(V4) %>%
    select(starts_with("V3")) %>%
    summarise_all("sum") %>%
    ungroup



b <- test2_tbl %>%
    left_join(test1_tbl, by=c("V1")) %>%
    group_by(V1) %>%
    select(starts_with("V3")) %>%
    summarise_all("sum") %>%
    ungroup

 a.local <- collect(a)
 b.local <- collect(b)

 a.local
\# A tibble: 3 × 3
     V4  V3_1  V3_2
  <chr> <dbl> <dbl>
1    M3   225     0
2    M2     0   225
3    M1   225   225
 b.local
\# A tibble: 3 × 3
     V1  V3_1  V3_2
  <chr> <dbl> <dbl>
1    M3   225     0
2    M2     0   225
3    M1   225   225
 left_join(a.local, b.local, by=c("V4"="V1"))
\# A tibble: 3 × 5
     V4 V3_1.x V3_2.x V3_1.y V3_2.y
  <chr>  <dbl>  <dbl>  <dbl>  <dbl>
1    M3    225      0    225      0
2    M2      0    225      0    225
3    M1    225    225    225    225
     left_join(a, b, by=c("V4"="V1"))
Source:   query [3 x 6]
Database: spark connection master=local[4] app=sparklyr local=TRUE

Ошибка: org.apache.spark.sql.AnalysisException: cannot resolve '`V3_1.x`' given input columns: [V3_1.y, V3_2.y, V4, V3_2.x, V1, V3_1.x]; line 1 pos 0
	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:77)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:74)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:301)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:301)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:300)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionUp$1(QueryPlan.scala:190)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2(QueryPlan.scala:200)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2$1.apply(QueryPlan.scala:204)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2(QueryPlan.scala:204)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$5.apply(QueryPlan.scala:209)
	at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:179)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:209)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:74)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:67)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:126)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:67)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:58)
	at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:49)
	at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:64)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withPlan(Dataset.scala:2589)
	at org.apache.spark.sql.Dataset.select(Dataset.scala:969)
	at org.apache.spark.sql.Dataset.selectExpr(Dataset.scala:1004)
	at sun.reflect.GeneratedMethodAccessor38.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at sparklyr.Invoke$.invoke(invoke.scala:94)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by krlmlr** [comment]
Thanks. Would you mind filing this with the [sparklyr repo](https://github.com/rstudio/sparklyr)? This doesn't look like a dplyr issue to me.

**Comment by p2004r** [comment]
Ok!  Crossposted in https://github.com/rstudio/sparklyr/issues/385

**Comment by p2004r** [comment]
In the spark names do not contain the "dot". 

```
left_join(a, b, by=c("V4"="V1"), suffix = c("_x", "_y"))
Source:   query [3 x 6]
Database: spark connection master=local[4] app=sparklyr local=TRUE

     V4 V3_1_x V3_2_x    V1 V3_1_y V3_2_y
  <chr>  <dbl>  <dbl> <chr>  <dbl>  <dbl>
1    M3    225      0    M3    225      0
2    M2      0    225    M2      0    225
3    M1    225    225    M1    225    225

```
